/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconDownload: typeof import('./components/Icon/IconDownload.vue')['default']
    IconGitee: typeof import('./components/Icon/IconGitee.vue')['default']
    IconGithub: typeof import('./components/Icon/IconGithub.vue')['default']
    IconMoon: typeof import('./components/Icon/IconMoon.vue')['default']
    IconSun: typeof import('./components/Icon/IconSun.vue')['default']
    MainHeader: typeof import('./components/MainHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
